import { Types, type ClientSession } from "mongoose";

// Models
import { type IUser } from "../Models/user.model.ts";
import Order, {
  type IOrder,
  type OrderStatus,
  type OrderType,
  type PaymentMethod,
  type PaymentStatus,
  type PaymentCollectionType,
} from "../Models/order.model.ts";
import OrderCounter from "../Models/order-counter.model.ts";

// Repositories
import { OrderItemRepository } from "./orderItem.repository.ts";
import { UserRepository } from "./user.repository.ts";

// Transitions
import { ORDER_STATUS_TRANSITIONS } from "../modules/Order/order.transition.ts";

// Utils
import AppError from "../Utils/AppError.ts";

/* =========================================================
   Types
========================================================= */
export type OrderAction =
  | "verify_payment"
  | "confirm"
  | "ship"
  | "deliver"
  | "cancel"
  | "return"
  | "refund";

export interface OrderWithAction extends IOrder {
  availableActions?: OrderAction[];
}

export interface CreateOrderData {
  user?: Types.ObjectId;
  cashier?: Types.ObjectId;

  items: Types.ObjectId[];

  orderType: OrderType;

  /* -------------------------------------------------------
     Financial Snapshot
  ------------------------------------------------------- */

  subtotal: number;
  discount: number;
  orderAmount: number;

  deliveryCharge: number;
  totalAmount: number;

  /* -------------------------------------------------------
     Cost & Profit
  ------------------------------------------------------- */

  totalCost: number;
  totalProfit: number;

  /* -------------------------------------------------------
     Payment
  ------------------------------------------------------- */

  paymentMethod: PaymentMethod;
  paymentCollectionType: PaymentCollectionType;

  paymentStatus: PaymentStatus;

  confirmationPaymentDue: number;
  prepaidAmount: number;
  amountDueOnDelivery: number;

  /* -------------------------------------------------------
     Coupon
  ------------------------------------------------------- */

  coupon?: Types.ObjectId;

  /* -------------------------------------------------------
     Delivery
  ------------------------------------------------------- */

  deliveryAddress: {
    name: string;
    phone: string;
    email: string;

    address: string;
    city: string;

    postalCode?: string;
    country?: string;
  };

  /* -------------------------------------------------------
     Misc
  ------------------------------------------------------- */

  orderNote?: string;

  /*
   * Usually generated by the repository/service.
   * Kept optional here so callers do not have to generate it.
   */
  orderNumber?: string;

  /*
   * Usually "pending" for online orders.
   */
  status?: OrderStatus;

  /*
   * Usually generated automatically.
   */
  inventoryReservedAt?: Date;
  inventoryReservationExpiresAt?: Date;
}

export interface OrderFilter {
  status?: OrderStatus | { $in: OrderStatus[] };
  orderType?: OrderType;
  paymentMethod?: PaymentMethod;
  paymentStatus?: PaymentStatus;
  user?: Types.ObjectId;
  cashier?: Types.ObjectId;
  coupon?: Types.ObjectId;
  createdAt?: {
    $gte?: Date;
    $lte?: Date;
  };
}

export interface OrderPagination {
  skip: number;
  limit: number;
}

/* =========================================================
   Repository
========================================================= */

export const OrderRepository = {
  /* =======================================================
     CREATE
  ======================================================= */

  async create(
    data: CreateOrderData,
    session?: ClientSession,
  ): Promise<IOrder> {
    const orderNumber = data.orderNumber ?? (await this.getNextOrderNumber());

    const order = new Order({
      ...data,
      orderNumber,

      /*
       * Let the service explicitly provide a status when needed.
       * Otherwise new orders start as pending.
       */
      status: data.status ?? "pending",
    });

    if (session) {
      order.$session(session);
    }

    return order.save();
  },

  /* =======================================================
     FIND BY ID
  ======================================================= */

  findById(orderId: Types.ObjectId, session?: ClientSession) {
    return Order.findById(orderId)
      .populate({
        path: "items",
        populate: {
          path: "product",
          select: "name slug variants",
        },
      })
      .populate("user", "name email phone")
      .populate("cashier", "name email")
      .populate("coupon")
      .session(session ?? null);
  },

  /* =======================================================
     FIND BY ORDER NUMBER
  ======================================================= */

  findByNumber(
    orderNumber: string,
    session?: ClientSession,
  ): Promise<IOrder | null> {
    return Order.findOne({ orderNumber })
      .populate({
        path: "items",
        populate: {
          path: "product",
          select: "name slug variants",
        },
      })
      .populate("user", "name email phone")
      .populate("cashier", "name email")
      .populate("coupon")
      .session(session ?? null);
  },

  /* =======================================================
     FIND BY ID WITH ITEMS
  ======================================================= */

  findByIdWithItems(orderId: Types.ObjectId, session?: ClientSession) {
    return Order.findById(orderId)
      .populate({
        path: "items",
        populate: {
          path: "product",
          select: "name slug variants",
        },
      })
      .session(session ?? null);
  },

  /* =======================================================
     FIND USER ORDERS
  ======================================================= */

  findUserOrders(
    userId: Types.ObjectId,
    filter: OrderFilter = {},
    pagination: OrderPagination,
    session?: ClientSession,
  ) {
    return Order.find({
      user: userId,
      ...filter,
    })
      .sort({ createdAt: -1 })
      .skip(pagination.skip)
      .limit(pagination.limit)
      .populate({
        path: "items",
        populate: {
          path: "product",
          select: "name slug variants",
        },
      })
      .session(session ?? null);
  },

  /* =======================================================
     FIND BY USER
  ======================================================= */

  findByUser(userId: Types.ObjectId, fields?: string, session?: ClientSession) {
    return Order.find({
      user: userId,
    })
      .select(fields ?? "-__v")
      .populate({
        path: "items",
        populate: {
          path: "product",
          select: "name slug variants",
        },
      })
      .session(session ?? null);
  },

  /* =======================================================
     FIND ALL
  ======================================================= */

  findAll(
    filter: OrderFilter = {},
    pagination: OrderPagination,
    session?: ClientSession,
  ) {
    return Order.find(filter)
      .sort({ createdAt: -1 })
      .skip(pagination.skip)
      .limit(pagination.limit)
      .populate({
        path: "items",
        populate: {
          path: "product",
          select: "name slug variants",
        },
      })
      .populate("user", "name email phone")
      .populate("cashier", "name email")
      .session(session ?? null);
  },

  /* =======================================================
     UPDATE
  ======================================================= */

  updateById(
    orderId: Types.ObjectId,
    updates: Partial<IOrder>,
    session?: ClientSession,
  ) {
    return Order.findByIdAndUpdate(
      orderId,
      { $set: updates },
      {
        new: true,
        runValidators: true,
        session: session ?? null,
      },
    );
  },

  /* =======================================================
     UPDATE STATUS
  ======================================================= */

  updateStatus(
    orderId: Types.ObjectId,
    status: OrderStatus,
    extra: Partial<IOrder> = {},
    session?: ClientSession,
  ) {
    return Order.findByIdAndUpdate(
      orderId,
      {
        $set: {
          status,
          ...extra,
        },
      },
      {
        new: true,
        runValidators: true,
        session: session ?? null,
      },
    );
  },

  /* =======================================================
     CONFIRM ORDER
  ======================================================= */

  async markConfirmed(
    orderId: Types.ObjectId,
    session?: ClientSession,
  ): Promise<IOrder> {
    const order = await Order.findOneAndUpdate(
      {
        _id: orderId,
        status: "pending",

        /*
         * Confirmation should only happen when
         * the required pre-confirmation payment
         * has been collected.
         */
        $expr: {
          $gte: ["$prepaidAmount", "$confirmationPaymentDue"],
        },
      },
      {
        $set: {
          status: "confirmed",
        },
      },
      {
        new: true,
        runValidators: true,
        session: session ?? null,
      },
    );

    if (!order) {
      throw new AppError(
        "Order not found or payment requirement has not been satisfied",
        400,
      );
    }

    return order;
  },

  /* =======================================================
     MARK SHIPPED
  ======================================================= */

  async markShipped(
    orderId: Types.ObjectId,
    shippedAt: Date,
    session?: ClientSession,
  ): Promise<IOrder> {
    const order = await Order.findOneAndUpdate(
      {
        _id: orderId,
        status: "confirmed",
      },
      {
        $set: {
          status: "shipped",
          shippedAt,
        },
      },
      {
        new: true,
        runValidators: true,
        session: session ?? null,
      },
    );

    if (!order) {
      throw new AppError("Order not found or cannot be marked as shipped", 400);
    }

    return order;
  },

  /* =======================================================
     MARK DELIVERED
  ======================================================= */

  async markDelivered(
    orderId: Types.ObjectId,
    deliveredAt: Date,
    session?: ClientSession,
  ): Promise<IOrder> {
    const order = await Order.findOneAndUpdate(
      {
        _id: orderId,
        status: "shipped",
      },
      {
        $set: {
          status: "delivered",
          deliveredAt,
        },
      },
      {
        new: true,
        runValidators: true,
        session: session ?? null,
      },
    );

    if (!order) {
      throw new AppError(
        "Order not found or cannot be marked as delivered",
        400,
      );
    }

    return order;
  },

  /* =======================================================
     CANCEL ORDER
  ======================================================= */

  async markCancelled(
    orderId: Types.ObjectId,
    cancelledBy: Types.ObjectId,
    cancellationReason: string,
    cancellationDate: Date = new Date(),
    session?: ClientSession,
  ): Promise<IOrder> {
    const order = await Order.findOneAndUpdate(
      {
        _id: orderId,
        status: {
          $in: ["pending", "confirmed"],
        },
      },
      {
        $set: {
          status: "cancelled",
          cancelledBy,
          cancellationReason,
          cancellationDate,
        },
      },
      {
        new: true,
        runValidators: true,
        session: session ?? null,
      },
    );

    if (!order) {
      throw new AppError("Order not found or cannot be cancelled", 400);
    }

    return order;
  },

  /* =======================================================
     MARK RETURNED
  ======================================================= */

  async markReturned(
    orderId: Types.ObjectId,
    session?: ClientSession,
  ): Promise<IOrder> {
    const order = await Order.findOneAndUpdate(
      {
        _id: orderId,
        status: "delivered",
      },
      {
        $set: {
          status: "returned",
        },
      },
      {
        new: true,
        runValidators: true,
        session: session ?? null,
      },
    );

    if (!order) {
      throw new AppError(
        "Order not found or cannot be marked as returned",
        400,
      );
    }

    return order;
  },

  /* =======================================================
     MARK REFUNDED
  ======================================================= */

  async markRefunded(
    orderId: Types.ObjectId,
    session?: ClientSession,
  ): Promise<IOrder> {
    const order = await Order.findOneAndUpdate(
      {
        _id: orderId,
        status: {
          $in: ["cancelled", "returned"],
        },
      },
      {
        $set: {
          status: "refunded",
        },
      },
      {
        new: true,
        runValidators: true,
        session: session ?? null,
      },
    );

    if (!order) {
      throw new AppError(
        "Order not found or cannot be marked as refunded",
        400,
      );
    }

    return order;
  },

  /* =======================================================
     PAYMENT
  ======================================================= */

  async updatePayment(
    orderId: Types.ObjectId,
    data: {
      prepaidAmount: number;
      paymentStatus: PaymentStatus;
      amountDueOnDelivery: number;
    },
    session?: ClientSession,
  ): Promise<IOrder> {
    const order = await Order.findByIdAndUpdate(
      orderId,
      {
        $set: {
          prepaidAmount: data.prepaidAmount,
          paymentStatus: data.paymentStatus,
          amountDueOnDelivery: data.amountDueOnDelivery,
        },
      },
      {
        new: true,
        runValidators: true,
        session: session ?? null,
      },
    );

    if (!order) {
      throw new AppError("Order not found", 404);
    }

    return order;
  },

  /* =======================================================
     PAYMENT STATUS
  ======================================================= */

  updatePaymentStatus(
    orderId: Types.ObjectId,
    paymentStatus: PaymentStatus,
    session?: ClientSession,
  ) {
    return Order.findByIdAndUpdate(
      orderId,
      {
        $set: {
          paymentStatus,
        },
      },
      {
        new: true,
        runValidators: true,
        session: session ?? null,
      },
    );
  },

  /* =======================================================
     COUNTS
  ======================================================= */

  count(filter: OrderFilter = {}, session?: ClientSession) {
    return Order.countDocuments(filter).session(session ?? null);
  },

  countUserOrders(
    userId: Types.ObjectId,
    filter: OrderFilter = {},
    session?: ClientSession,
  ) {
    return Order.countDocuments({
      user: userId,
      ...filter,
    }).session(session ?? null);
  },

  /* =======================================================
     FIRST TIME CUSTOMER
  ======================================================= */

  async isFirstTimeCustomer(
    userId: Types.ObjectId,
    session?: ClientSession,
  ): Promise<boolean> {
    const exists = await Order.exists({
      user: userId,

      /*
       * Do not consider abandoned/pending orders
       * as a completed customer purchase.
       */
      status: {
        $in: ["confirmed", "shipped", "delivered", "returned", "refunded"],
      },
    }).session(session ?? null);

    return !exists;
  },

  /* =======================================================
     ORDER NUMBER
  ======================================================= */

  async getNextOrderNumber(): Promise<string> {
    const today = new Date();

    const datePart = today.toISOString().slice(0, 10).replace(/-/g, "");

    const counter = await OrderCounter.findOneAndUpdate(
      {
        key: `order_${datePart}`,
      },
      {
        $inc: {
          seq: 1,
        },
      },
      {
        new: true,
        upsert: true,
      },
    );

    if (!counter) {
      throw new AppError("Unable to generate order number", 500);
    }

    const sequence = String(counter.seq).padStart(6, "0");

    return `ORD-${datePart}-${sequence}`;
  },

  async getAvailableOrderActions(status: OrderStatus): Promise<OrderAction[]> {
    switch (status) {
      case "pending":
        return ["verify_payment", "confirm", "cancel"];

      case "confirmed":
        return ["ship", "cancel"];

      case "shipped":
        return ["deliver"];

      case "delivered":
        return ["return"];

      case "returned":
        return ["refund"];

      case "cancelled":
        return ["refund"];

      case "refunded":
        return [];

      default:
        return [];
    }
  },

  async confirmOrder(
    orderId: Types.ObjectId,
    session?: ClientSession,
  ): Promise<IOrder> {
    const order = await Order.findOneAndUpdate(
      {
        _id: orderId,
        status: "pending",
      },
      {
        $set: {
          status: "confirmed",
        },
      },
      {
        new: true,
        runValidators: true,
        session: session ?? null,
      },
    );

    if (!order) {
      throw new AppError("Order not found or cannot be confirmed.", 400);
    }

    return order;
  },

  async updateManualPayment(
    order: IOrder,
    amount: number,
    session?: ClientSession,
  ): Promise<IOrder> {
    const newPrepaidAmount = order.prepaidAmount + amount;

    if (newPrepaidAmount > order.confirmationPaymentDue) {
      throw new AppError(
        "Payment amount exceeds the confirmation payment due.",
        400,
      );
    }

    order.prepaidAmount = newPrepaidAmount;

    order.paymentStatus =
      newPrepaidAmount >= order.confirmationPaymentDue
        ? "completed"
        : "partial";

    return order.save({
      session: session ?? null,
    });
  },

  async adminOrderDetails(
    user: IUser,
    order: IOrder,
  ): Promise<OrderWithAction> {
    const orderItems = await OrderItemRepository.findManyByIds(order.items);

    const isActionAllowed = user.role === "admin" || user.role === "customer";

    let userFields =
      "name email phone isEmailVerified isPhoneVerified verified role createdAt updatedAt";

    const orderData = {
      ...order.toObject(),
      items: orderItems,
      ...(isActionAllowed && {
        user: await UserRepository.getUserById(order.user, userFields),
        availableActions: await OrderRepository.getAvailableOrderActions(
          order.status,
        ),
      }),
    };

    return orderData;
  },

  async transitionOrderStatus(
    user: IUser,
    orderNumber: string,
    currentStatus: OrderStatus,
    nextStatus: OrderStatus,
    update: Record<string, unknown> = {},
    session?: ClientSession,
  ) {
    const order = await Order.findOneAndUpdate(
      {
        orderNumber,
        status: currentStatus,
      },
      {
        $set: {
          status: nextStatus,
          ...update,
        },
      },
      {
        new: true,
        runValidators: true,
        ...(session ? { session } : {}),
      },
    );

    if (!order) {
      return null;
    }

    let orderdata = await OrderRepository.adminOrderDetails(user, order);

    return orderdata;
  },
};
